### PR TITLE
Some minor edits.

### PR DESCRIPTION
**Pull request by masterleinad**
@bangerth Here's your PR, referencing https://github.com/dealii/dealii/pull/6747#pullrequestreview-226421405 .:wink:

### CODE REVIEW

**Comment by bangerth** [comment]
Ah, thanks @masterleinad -- how did you do this? From my account, I tried to create a PR against @dangars 's repo but it did not show up in the list of possible repos...

@dangars -- FYI.

**Comment by masterleinad** [comment]
>  I tried to create a PR against @dangars 's repo but it did not show up in the list of possible repos...

I couldn't see it either but manually modifying the URL worked.

**Comment by dangars** [comment]
I don't know why it didn't work. Maybe I should activate a particular option?

**Comment by bangerth** [comment]
On 4/15/19 10:45 AM, Daniel Garcia-Sanchez wrote:
> I don't know why it didn't work. Maybe I should activate a particular 
> option?

Good question. There is an option somewhere that allows people to push 
commits into your repository, but it's possible that that only works for 
active pull requests.

Whatever the reason, you now have these changes :-)

**Pull request merged**
